[package]
name = "eidoplot-dsl"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
miette = { workspace = true, optional = true }

[features]
diag = ["dep:miette"]
