[package]
name = "eidoplot-dsl"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
miette = { version = "7.6.0", optional = true }

[features]
diag = ["dep:miette"]
