[package]
name = "eidoplot-pxl"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
eidoplot = { path = "../eidoplot" }
eidoplot-svg = { path = "../eidoplot-svg" }
resvg = "0.45.1"
tiny-skia = "0.11.4"
usvg = "0.45.1"
